# Generated by Django 3.0 on 2020-01-30 01:19

import django.core.validators
from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(validators=[server.models.max_date_validator])),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('annotation', models.CharField(max_length=1000)),
                ('pages', models.IntegerField()),
                ('publication_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2020)])),
                ('price', models.FloatField()),
                ('rating', models.IntegerField()),
                ('authors', models.ManyToManyField(to='server.Author')),
            ],
        ),
    ]
