# Generated by Django 3.0 on 2020-02-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20200201_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_of_birth',
            new_name='birthday',
        ),
    ]
